import type { Metadata } from "next";
import { SITE_NAME, CONTENT_LAST_UPDATED } from "@/lib/seo";
import InfoPageLayout from "@/components/InfoPageLayout";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: `${SITE_NAME} provides general educational information and financial planning tools, not regulated professional advice.`,
  alternates: { canonical: "/disclaimer" },
};

export default function DisclaimerPage() {
  return (
    <InfoPageLayout title="Disclaimer" lastUpdated={CONTENT_LAST_UPDATED}>
      <section>
        <p className="rounded-xl border border-warn/30 bg-paper-100/60 p-5 leading-relaxed">
          {SITE_NAME} provides general educational information and financial planning tools. It
          does not provide investment, tax, legal, insurance, or other regulated professional
          advice.
        </p>
      </section>

      <section>
        <h2 className="font-display text-lg font-semibold text-ink-900">
          Educational purpose only
        </h2>
        <p className="mt-2 leading-relaxed">
          Every calculator, guide, and AI-generated suggestion on this site is intended to help
          you understand general financial concepts and see illustrative numbers — not to
          recommend specific financial products, investments, or actions for your individual
          circumstances.
        </p>
      </section>

      <section>
        <h2 className="font-display text-lg font-semibold text-ink-900">
          No guaranteed outcomes
        </h2>
        <p className="mt-2 leading-relaxed">
          Calculators use standard financial formulas applied to the numbers and assumptions you
          enter (interest rates, expected returns, timelines). Actual results — from loans,
          investments, or savings — will differ based on real-world rates, fees, taxes, and
          market performance, none of which this site can predict or guarantee.
        </p>
      </section>

      <section>
        <h2 className="font-display text-lg font-semibold text-ink-900">
          AI-generated content
        </h2>
        <p className="mt-2 leading-relaxed">
          The financial planner's roadmap and priorities are generated by an AI model based on
          the information you provide. AI-generated suggestions may be incomplete, generic, or
          occasionally incorrect, and should be treated as a starting point for your own
          thinking — not a personalized recommendation from a licensed advisor.
        </p>
      </section>

      <section>
        <h2 className="font-display text-lg font-semibold text-ink-900">
          When to consult a professional
        </h2>
        <p className="mt-2 leading-relaxed">
          For decisions involving significant sums, taxes, legal matters, insurance, or complex
          investment products, consult a licensed financial advisor, chartered accountant, or
          other relevant professional who can consider your complete financial situation.
        </p>
      </section>
    </InfoPageLayout>
  );
}
